In [69]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [70]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.thing = nn.Parameter(torch.rand(10), requires_grad=True)
    
    def forward(self):
        return self.thing

In [71]:
net = Net()

learning_rate = 0.1

loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate)

In [73]:
ideal_weights = torch.tensor([0.0027] * 10)
for epoch in range(100):
    optimizer.zero_grad()
    pred = net()
    print(pred)

    weight = torch.zeros(10)
    for i in range(10):
        if pred[i].item() > 0.5:
            weight[i] = 0.0027
        else:
            weight[i] = 0.00783
    
    total_loss = ideal_weights - weight
    print(ideal_weights)
    print(weight)
    print(total_loss)

    loss = loss_fn(pred, total_loss.float())
    print(loss)
    loss.backward()
    optimizer.step()

Parameter containing:
tensor([6.9508e-02, 1.0427e-01, 7.4097e-02, 8.1494e-05, 1.3743e-02, 9.7821e-02,
        7.7188e-02, 3.5304e-02, 7.1455e-02, 1.2906e-02], requires_grad=True)
tensor([0.0027, 0.0027, 0.0027, 0.0027, 0.0027, 0.0027, 0.0027, 0.0027, 0.0027,
        0.0027])
tensor([0.0078, 0.0078, 0.0078, 0.0078, 0.0078, 0.0078, 0.0078, 0.0078, 0.0078,
        0.0078])
tensor([-0.0051, -0.0051, -0.0051, -0.0051, -0.0051, -0.0051, -0.0051, -0.0051,
        -0.0051, -0.0051])
tensor(0.0049, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([ 6.8015e-02,  1.0208e-01,  7.2512e-02, -2.2736e-05,  1.3365e-02,
         9.5762e-02,  7.5541e-02,  3.4495e-02,  6.9923e-02,  1.2545e-02],
       requires_grad=True)
tensor([0.0027, 0.0027, 0.0027, 0.0027, 0.0027, 0.0027, 0.0027, 0.0027, 0.0027,
        0.0027])
tensor([0.0078, 0.0078, 0.0078, 0.0078, 0.0078, 0.0078, 0.0078, 0.0078, 0.0078,
        0.0078])
tensor([-0.0051, -0.0051, -0.0051, -0.0051, -0.0051, -0.0051, -0.0051, -0.0051,
       