In [350]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import random
import numpy as np

In [351]:
# class Net(nn.Module):
#     def __init__(self):
#         super(Net, self).__init__()
#         self.thing = nn.Parameter(torch.rand(10), requires_grad=True)
    
#     def forward(self):
#         return self.thing

In [352]:
# net = Net()

# learning_rate = 0.1

# loss_fn = nn.MSELoss()

# optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate)

In [353]:
# ideal_weights = torch.tensor([0.0027] * 10)
# for epoch in range(100):
#     optimizer.zero_grad()
#     pred = net()
#     print(pred)

#     weight = torch.zeros(10)
#     for i in range(10):
#         if pred[i].item() > 0.5:
#             weight[i] = 0.0027
#         else:
#             weight[i] = 0.00783
    
#     total_loss = ideal_weights - weight
#     print(ideal_weights)
#     print(weight)
#     print(total_loss)

#     loss = loss_fn(pred, total_loss.float())
#     print(loss)
#     loss.backward()
#     optimizer.step()

In [354]:
# class customAutograd(torch.autograd.Function):
#     @staticmethod
#     def forward(ctx, input):
#         """
#         In the forward pass we receive a Tensor containing the input and return
#         a Tensor containing the output. ctx is a context object that can be used
#         to stash information for backward computation. You can cache arbitrary
#         objects for use in the backward pass using the ctx.save_for_backward method.
#         """
#         ctx.save_for_backward(input)
#         return input / 2

#     @staticmethod
#     def backward(ctx, grad_output):
#         """
#         In the backward pass we receive a Tensor containing the gradient of the loss
#         with respect to the output, and we need to compute the gradient of the loss
#         with respect to the input.
#         """
#         input, = ctx.saved_tensors
#         return grad_output * input

In [355]:
class testNet(nn.Module):
    def __init__(self):
        super(testNet, self).__init__()
        torch.manual_seed(12)
        self.elem_material = nn.Parameter(torch.rand(10), requires_grad=True)
    
    def forward(self):
        print(self.elem_material)

        E_vector = 131 / (1 + torch.exp(-10 * (self.elem_material - torch.tensor([0.5] * 10)))) + 69
        Stif = E_vector * 10
        u = Stif / 2

        return u


In [356]:
net = testNet()

num_epochs = 10
learning_rate = 1
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate)

ideal_u = torch.tensor([5.0] * 10)

for epoch in range(num_epochs):
    optimizer.zero_grad()
    u = net()

    loss = loss_fn(u, ideal_u)
    loss.backward()

    for name, param in net.named_parameters():
        if param.requires_grad:
            print(name, param.grad)

    optimizer.step()

Parameter containing:
tensor([0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
        0.7224], requires_grad=True)
elem_material tensor([194599.2812,  30276.1992, 183279.0469, 218446.6406, 141193.3125,
         10670.0410, 182258.2031,  33139.8281, 100560.4609, 107408.7109])
Parameter containing:
tensor([-194598.8125,  -30275.9668, -183278.5938, -218446.0469, -141192.9062,
         -10669.9141, -182257.5625,  -33139.5859, -100559.7266, -107407.9922],
       requires_grad=True)
elem_material tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
Parameter containing:
tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], requires_grad=True)
elem_material tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
Parameter containing:
tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], requires_grad=True)
elem_material tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
Parameter containing:
tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan